# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./
COPY tsconfig.json ./

# Install dependencies (skip prepare scripts to avoid running build twice)
RUN npm install --ignore-scripts

# Build the project
COPY src ./src
RUN npm run build

# Set executable permissions for build/index.js if not already
RUN chmod +x build/index.js

# Expose port if needed (not specified, but using stdio)

# Start the MCP server using stdio transport as per Smithery configuration
CMD ["node", "build/index.js"]
